# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameinfo', '0002_auto_20160930_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('sessions', models.IntegerField()),
                ('duration', models.DurationField()),
                ('enableflag', models.BooleanField()),
                ('gamedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Details')),
            ],
        ),
    ]
