# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameinfo', '0003_position'),
        ('customer', '0007_auto_20160930_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('leadgeneratedtime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('gamedetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Details')),
            ],
        ),
    ]
