# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Improve_customer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('improve_customer_name', models.CharField(max_length=255)),
                ('improve_customer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('improve_mobile_number', models.CharField(max_length=10)),
                ('improve_amount_paid', models.CharField(max_length=30)),
                ('improve_membership_start_date', models.CharField(max_length=30)),
                ('improve_membership_end_date', models.CharField(max_length=30)),
                ('improve_preferred_monday', models.CharField(max_length=1)),
                ('improve_monday_fixture', models.CharField(max_length=4)),
                ('improve_preferred_tuesday', models.CharField(max_length=1)),
                ('improve_tuesday_fixture', models.CharField(max_length=4)),
                ('improve_preferred_wednesday', models.CharField(max_length=1)),
                ('improve_wednesday_fixture', models.CharField(max_length=4)),
                ('improve_preferred_thursday', models.CharField(max_length=1)),
                ('improve_thursday_fixture', models.CharField(max_length=4)),
                ('improve_preferred_friday', models.CharField(max_length=1)),
                ('improve_friday_fixture', models.CharField(max_length=4)),
                ('improve_preferred_saturday', models.CharField(max_length=1)),
                ('improve_saturday_fixture', models.CharField(max_length=4)),
                ('improve_preferred_sunday', models.CharField(max_length=1)),
                ('improve_sunday_fixture', models.CharField(max_length=4)),
                ('improve_preferred_position', models.CharField(max_length=30)),
                ('improve_self_rating', models.CharField(max_length=30)),
                ('improve_number_games_left', models.CharField(max_length=30)),
                ('improve_flexi_flag', models.CharField(max_length=10)),
                ('improve_batch_type', models.CharField(max_length=10)),
                ('improve_preferred_venue', models.CharField(max_length=10)),
                ('improve_about_me', models.CharField(max_length=10)),
                ('improve_customer_picture', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Initial_customer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=255)),
                ('customer_password', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('customer_mobile_number', models.CharField(max_length=255)),
                ('play_customer_id', models.CharField(max_length=255)),
                ('improve_customer_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Play_customer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('play_customer_name', models.CharField(max_length=255)),
                ('play_customer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('play_mobile_number', models.CharField(max_length=10)),
                ('play_amount_paid', models.CharField(max_length=100)),
                ('play_membership_start_date', models.CharField(max_length=30)),
                ('play_membership_end_date', models.CharField(max_length=30)),
                ('play_preferred_monday', models.CharField(max_length=1)),
                ('play_monday_fixture', models.CharField(max_length=4)),
                ('play_preferred_tuesday', models.CharField(max_length=1)),
                ('play_tuesday_fixture', models.CharField(max_length=4)),
                ('play_preferred_wednesday', models.CharField(max_length=1)),
                ('play_wednesday_fixture', models.CharField(max_length=4)),
                ('play_preferred_thursday', models.CharField(max_length=1)),
                ('play_thursday_fixture', models.CharField(max_length=4)),
                ('play_preferred_friday', models.CharField(max_length=1)),
                ('play_friday_fixture', models.CharField(max_length=4)),
                ('play_preferred_saturday', models.CharField(max_length=1)),
                ('play_saturday_fixture', models.CharField(max_length=4)),
                ('play_preferred_sunday', models.CharField(max_length=1)),
                ('play_sunday_fixture', models.CharField(max_length=4)),
                ('play_preferred_position', models.CharField(max_length=30)),
                ('play_self_rating', models.CharField(max_length=30)),
                ('play_number_games_left', models.CharField(max_length=30)),
                ('play_flexi_flag', models.CharField(max_length=10)),
                ('play_batch_type', models.CharField(max_length=10)),
                ('play_preferred_venue', models.CharField(max_length=10)),
                ('play_about_me', models.CharField(max_length=10)),
                ('play_customer_picture', models.CharField(max_length=10)),
            ],
        ),
    ]
