# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0004_auto_20160930_0533'),
        ('gameinfo', '0002_auto_20160930_0533'),
        ('customer', '0002_auto_20160930_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepreference',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixture.Fixture'),
        ),
        migrations.AddField(
            model_name='gamepreference',
            name='gameday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Day'),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='gamedetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Details'),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='gamelevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Level'),
        ),
        migrations.AddField(
            model_name='customerlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
