# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20160930_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='package',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
