# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0003_position'),
        ('customer', '0005_auto_20160930_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevel',
            name='gameposition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Position'),
            preserve_default=False,
        ),
    ]
