# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_gamelevel_gameposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='S', max_length=100),
            preserve_default=False,
        ),
    ]
