# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20160930_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerpic',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
