# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        ('customer', '0005_auto_20160930_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startdate', models.DateField(max_length=255)),
                ('enddate', models.DateField(max_length=255)),
                ('sessionsleft', models.IntegerField()),
                ('flexiflag', models.BooleanField()),
                ('expiryflag', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Package')),
            ],
        ),
    ]
