# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameinfo', '0001_initial'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venuename', models.CharField(max_length=100)),
                ('venuepic', models.ImageField(upload_to='')),
                ('logicalarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.LogicalArea')),
            ],
        ),
        migrations.CreateModel(
            name='VenueGamesavailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gamedetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.GameDetails')),
                ('venuedetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.VenueDetails')),
            ],
        ),
    ]
