# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookeddate', models.DateField(max_length=255)),
                ('gamedate', models.DateField(max_length=255)),
                ('joinstatus', models.BooleanField()),
                ('batchtype', models.CharField(choices=[(b'HOME', b'Home'), (b'FLEXI', b'Flexi'), (b'DEMO', b'Demo')], default=b'HOME', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FootballImproveProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('receiving', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('attacking', models.IntegerField()),
                ('teamname', models.CharField(max_length=10)),
                ('goalfor', models.IntegerField()),
                ('goalagainst', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('goalpoints', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('assistpoints', models.IntegerField()),
                ('upperbody', models.IntegerField()),
                ('lowerbody', models.IntegerField()),
                ('core', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('flexibility', models.CharField(choices=[(b'NONE', b'Not Taken'), (b'POOR', b'Poor'), (b'AVERAGE', b'Average'), (b'GOOD', b'Good'), (b'EXCELLENT', b'Excellent')], default=b'NONE', max_length=15)),
                ('bookinglog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingLog')),
            ],
        ),
        migrations.CreateModel(
            name='FootballPlayProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('receiving', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('attacking', models.IntegerField()),
                ('teamname', models.CharField(max_length=10)),
                ('goalfor', models.IntegerField()),
                ('goalagainst', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('goalpoints', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('assistpoints', models.IntegerField()),
                ('goalconceded', models.IntegerField()),
                ('cleansheet', models.IntegerField()),
                ('resultpoints', models.IntegerField()),
                ('bonuspoints', models.IntegerField()),
                ('matchpoints', models.IntegerField()),
                ('formmeter', models.IntegerField()),
                ('processedflag', models.BooleanField()),
                ('bookinglog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingLog')),
            ],
        ),
    ]
