# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_bookinglog_customer'),
        ('fixture', '0004_auto_20160930_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglog',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixture.Fixture'),
        ),
    ]
