# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Improve_game_slot_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('improve_fixture_id', models.IntegerField(max_length=255)),
                ('improve_game_day', models.CharField(max_length=255)),
                ('improve_venue_id', models.IntegerField(max_length=10)),
                ('improve_game_slot', models.CharField(max_length=100)),
                ('improve_court_name', models.CharField(max_length=30)),
                ('improve_game_max_players', models.IntegerField(max_length=30)),
                ('improve_home_batch_takein', models.IntegerField(max_length=10)),
                ('improve_home_batch_start_time', models.CharField(max_length=10)),
                ('improve_flexi_batch_start_time', models.CharField(max_length=10)),
                ('improve_general_cut_off', models.CharField(max_length=10)),
                ('improve_game_version', models.CharField(max_length=5)),
                ('improve_game_rating', models.CharField(max_length=15)),
                ('improve_enable_fixture', models.CharField(max_length=4)),
                ('improve_fixture_reminder_sent', models.CharField(max_length=255)),
                ('improve_flexi_fixture_reminder_sent', models.CharField(max_length=255)),
                ('improve_no_buddy_required', models.IntegerField(max_length=10)),
                ('improve_session_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Play_game_slot_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('play_fixture_id', models.IntegerField(max_length=255)),
                ('play_game_day', models.CharField(max_length=255)),
                ('play_venue_id', models.IntegerField(max_length=10)),
                ('play_game_slot', models.CharField(max_length=100)),
                ('play_court_name', models.CharField(max_length=30)),
                ('play_game_max_players', models.IntegerField(max_length=30)),
                ('play_home_batch_takein', models.IntegerField(max_length=10)),
                ('play_home_bacth_start_time', models.CharField(max_length=10)),
                ('play_flexi_batch_start_time', models.CharField(max_length=10)),
                ('play_general_cut_off', models.CharField(max_length=10)),
                ('play_game_version', models.CharField(max_length=5)),
                ('play_game_rating', models.CharField(max_length=15)),
                ('play_enable_fixture', models.CharField(max_length=4)),
                ('play_fixture_reminder_sent', models.CharField(max_length=255)),
                ('play_flexi_fixture_reminder_sent', models.CharField(max_length=255)),
                ('play_assigned_buddy1', models.IntegerField(max_length=10)),
                ('play_assigned_buddy2', models.IntegerField(max_length=10)),
                ('play_temp_buddy1', models.IntegerField(max_length=10)),
                ('play_temp_buddy2', models.IntegerField(max_length=10)),
                ('play_session_description', models.CharField(max_length=255)),
            ],
        ),
    ]
