# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_auto_20160923_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play_game_slot_details',
            old_name='play_home_bacth_start_time',
            new_name='play_home_batch_start_time',
        ),
    ]
