# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0005_auto_20160930_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='gamedescription',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
